// utils/demoData.ts

// Helper function to convert date strings to Date objects
const toDateObject = (dateStr: string): Date => {
  return new Date(dateStr);
};

// Helper to generate random dates within a range
const getRandomDate = (start: Date, end: Date): Date => {
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
};

// Helper to get random status
const getRandomStatus = (): string => {
  const statuses = ['Open', 'In-Progress', 'Implemented', 'Closed', 'Rejected'];
  const weights = [0.4, 0.25, 0.2, 0.1, 0.05];
  const random = Math.random();
  let cumulative = 0;
  for (let i = 0; i < statuses.length; i++) {
    cumulative += weights[i];
    if (random < cumulative) return statuses[i];
  }
  return 'Open';
};

// Helper to get random eligibility
const getRandomEligibility = (): string => {
  return Math.random() > 0.2 ? 'Yes' : 'No';
};

// Source options with weights
const sourceOptions = [
  'Apex', 'BHM', 'DSS', 'IM', 'HRA', 'PSM', 'Fire Audit', 
  'Internal Audit', 'External Audit', 'Linewalk', 'MOC', 'PHA'
];

const plantOptions = [
  'All', 'SMS1', 'SMS2', '1200 O2', 'CGP', 'CU Opn', 'CO', 'BF', 
  'DRI', 'PP', 'H2', 'G11', 'H11', 'CRM', 'LOG', 'SP'
];

const locationOptions = ['Angul', 'Raipur', 'Bhubaneswar'];
const sectionOptions = ['Operations', 'Maintenance', 'Safety', 'Quality', 'Process Control', 'Mechanical', 'Electrical'];
const equipmentTypes = ['NA', 'Conveyor', 'Crane', 'Furnace', 'Compressor', 'Pump', 'Valve', 'Detector', 'Analyzer'];

// Complete recommendation descriptions array with all provided records
const recommendationDescriptions = [
  // Original records
  'Centralized ARC to be done for structural integrity and all the requirements to be collated for the same and all technical requirements and documentation to be collated centrally for consistency and traceability.',
  'PM instructed to centrally collate plant-wide scaffolding data, including total tonnage requirements, total cubic meter area required so that this data will support planning, cost control, and for central ARC.',
  'Additional CO2 detector to be installed in adsorber outlet to ensure accurate reading.',
  'CO2 analyser calibration frequency to be increased from 4 months to shorter duration & CO2 analyser accuracy of reading should be periodically compared with quality control sampling.',
  'Field air intake CO2 analyser to initiate an alarm for the operator to take action on high CO2 detection.',
  'Field /atmospheric hydrocarbon detector (mainly methane) near compressor air intake with hooter to be provided with standard operating procedure for the specific action by the operator upon detection of high hydrocarbon and auto closure /reduction of IGV of MAC.',
  'Air suction provision during hot work to be implemented',
  'Dispersion analysis for the nearby gas pipeline to confirm the quantity & probability of hydrocarbon ingress into compressor air intake to be ascertained',
  'Regeneration timer to start after reaching the required temperature & regeneration flow for both nitrogen and air',
  'Provide audio visual alarm in case of refrigeration system trip, also define operator action on the refrigeration trip alarm in SOP.',
  'Adsorber low pressure trip to be provided',
  'Gas detector in office building HVAC air intake line to be confirmed',
  'Reduce the occupancy in CRM 1 building',
  'Sprinkler system for ammonia unloading pump with auto activation',
  'High pressure of the bullet should stop the feed XV & feed Pump',
  'Auto activation of sprinkler system upon activation of any two field gas detector activation in Ammonia Bullet',
  'Auto flaring option on high pressure',
  '100 2 voting for level transmitter to be considered',
  'Flame detector near the bullet to activate the deluge system automatically',
  'Sprinklers to be provided to the loading pump',
  'Explore the feasibility of flaring at low temperature like changing the pipe metallurgy from CS to SS for flare line portion',
  'Excess flow check valve',
  'Auto open close solenoid valve for sampling with timer based operations',
  'Stray current detection system to trip the recovery',
  'Flame proof electrical fittings (ATEX certified) to be installed near gas holder and gas lines (based on gas dispersion analysis)',
  'Corrosion proof painting and coating on structures and pipeline',
  'Thickness rebuilding coating of the welding joints of bellow/elbows/bends & other points may be considered.',
  'Install an additional valve with compatible metallurgy for gate and valve seat',
  'Barricading the seal pot/U-seal areas and displaying Signages of Restricted Area',
  'All Drain Points of Sealpot to be dummied',
  'SS Grade Piping to be replaced in HPLA line with Carbon alloy steel pipes',
  'Providing gas detectors with hooters with loop to control room to be evaluated',
  'All Vent lines to be provided with double isolation valves',
  'Providing level transmitter with low level alarm for all the seal pots may be considered',
  'A flame detection to be provided for pilot burner at the flare stack.',
  'Connect the pilot burners with different source of fuel to ensure that pilot burners are always in burning conditions.',
  'Conduct a fire water demand study, adequacy of fire water pumps capacity, other resources like communication equipment, F&G detection, siren and alarms required for emergency response based on risk scenario listed and implement the recommendations for the full facility',
  'Ladle leftover thickness scanner machine and connected to crane movement system to stop the lifting of down ladle /stopping the tapping LTC for down ladle',
  'Barcode scanner with unique barcode to identify the ladle from raipur to angul connected to QA/QC recording system',
  'Bund wall in ladle movement area to contain the hot steel',
  'Ladle tracking system to track the operational history and auto control for tapping',
  'Secondary containment /dike wall in crane movement area to be constructed to contain the hot steel leakage into shop floor level',
  'Thermographic scanner to detect the failure of refractory and auto control of tapping for down ladle in case of high outer wall temperature',
  'Data logger to capture the refractory temperature after ladle pre-heating at NFC filling area before tap and the pop-up message/alarm will be provided in HMI incase of refractory not meet the temperature.',
  'Ladle tracking system will update all the details of refractory used in the particular ladle.',
  'Ladle tracking system should not allow further movement of ladle in case of failure of thermal scanning.',
  'Thermal monitoring system of ladle during process at LRF',
  'Ladle tracking system will monitor the purging time and accordingly purging plug will be changed',
  'Steel dumping pit to be provided',
  'Ladle tracking system to incorporate the alert mechanism for excess ladle holding time and reladling provision to be made',
  'Level-2 system to be implemented for auto material discharge and arcing as per grade',
  'Ladle tracking to consider ladle steel temperature and accordingly ladle heat cycle adjusted',
  'Explore the feasibility of continuous temperature monitoring of steel during process',
  'Power consumption with respect to temperature setpoint to trip the arc to be implemented',
  'Ladle management system to be implemented with level sensor',
  'Ladle level measurement system to be implemented with interlock to BOF/NOF tilting system',
  'Explore the feasibility to detect the angular pulling or sway',
  'Camera focusing to hook display could be provided to operator',
  'Ladle automatic tilting system to be implemented',
  'Third party certification for crane operator',
  'Emergency lighting to be provided for critical crane operation location',
  'Dedicated DG for ladle cranes along with auto power change over system to be implemented',
  'Crane Hooter will trigger if crane holding with ladle (300T approx.) for 15mins',
  'OEM recommendation of replacement of critical components (Detailed study including FMEA is required)',
  'Emergency brake to be provided in rope drum collar',
  'Crane load chart/Load cell indication interlock with crane movement to be provided in crane cabin',
  'Two individual limit switches to be provided for slow down and end stop in both direction.',
  'Metal stamping on the rope with complete details of rope and replacement date. Feasibility of bar code scanner system installation',
  'Safety Guidelines by ministry to be followed for rope replacement',
  'NDT test of wire rope along with calculation of UTS and elasticity',
  'Third party audit to be engaged for testing of received wire rope',
  'Re-rating of liquid steel crane as per standard',
  'Laser sensor for angular pulling and trip crane accordingly',
  'Vibration sensor for measuring vibration of idler pin to be installed and to be interlocked with PLC',
  'Ladle level sensor will stop further tilting of converter in tapping side (Ladle tracking system)',
  'Ladle tracking system will monitor the welding quality',
  'Ladle tracking system will monitor ladle data from OEM',
  'Ladle tracking system will have data of bell arm and replacement alert will be given',
  'UT test of trunnion to be done once in year and to be incorporated with ladle tracking system',
  'Vibration sensor for motors and trip system to be implemented',
  'Hose fitting size could be installed in different sizes so that interchange of hose is not possible (Site specific study to be initiated and recommendations to be released)',
  'High capacity DG pump to pump industrial water to emergency overhead tank',
  'Interconnection of emergency overhead tank discharge line with secondary cooling line (with isolation valve)',
  'Anti corrosive painting',
  'Corrosion Test - pipe thickness',
  'Lance holder with PRV for tap hole lancing',
  'Flow meter for water line in mist cooling and major alarm in water flow is more than 3-4lpm',
  'Control valve in mist cooling water line to control the water flow',
  'Inclination indicator for tap hole drill machine',
  'Ultrasonic thickness measurement - hearth carbon block thickness',
  'Periodical replacement of rubber ring (25 days)',
  'Cover plate lifting mechanism to be provided to open/close the cover',
  'Provide the steam ring over the gasifier manhole flange to reduce the impact.',
  'Installation of Ash analyzer to stabilize the operating temperature',
  'New CO Field gas detectors (tag no) with alarm',
  'Involve third party for inspection of corrosion and erosion',
  'Install flow meter for monitoring nitrogen flow',
  'Improve in raw material quality (CCS,RDI) - Separate study to be initiated',
  'Coal particle size analyzers like camera/online screeners',
  'Online monitoring of CO in flue gas at Boiler outlet with audio alarm.',
  'Audible alarm to be provided.',
  'Flame scanners to be upgraded.',
  'Installation of ERV with auto logic pressure set point in the MS line before MSSV',
  'Upgradation of DCS is required for better automation.',
  'Boiler furnace explosion protection door to be provided',
  'Emergency Hard-stop push button in control room in case of DCS failure',
  'Sensor to be provided to check level and alarm in HMI',
  'Emergency shower to be provided in billet caster',
  'Toilet water drain line to be repaired with permanent solution - Technical study on adequacy to be done and recommendations to be implemented',
  'Scrap yard side sheeting to be provided to minimum level',
  'Control room glasses to be replaced with brick wall/shutter to be provided',
  'Parapet arrangement or side walls to be provided',
  'Steel grill to be provided in front of glass for crane operator cabin',
  'Reheater spray Control system auto operation',
  'Feed low moisture Fuel in boiler - Technical study with necessary modification to be conducted',
  'Choking in Super Heater coil (Internal scaling due to poor water chemistry) - Independent technical study to be conducted',
  'Provide online coal GCV analyzer',
  'Proper blending of fuel before feed to bunker',
  'Provide online coal Moisture analyzer',
  'Provide online coal size analyzer',
  'Condensate Drain Valves: Install automated or manual condensate drain valves in strategic locations to ensure water is drained properly from low points in the system - Technical design review on steam loop condensate drain system',
  'Leak Detection Systems: Use advanced leak detection systems to quickly identify and address any leaks at pipe joints, flanges, or threaded connections.',
  'Condensate Level Sensors: Install level sensors in low points and condensate collection areas to detect water buildup and initiate drainage automatically.',
  'Implement HIPPS as very critical. HIPPS requires independent SIL-rated pressure sensing (2oo3 voting), a dedicated SIL-certified logic solver, and fast-acting fail-closed ESD valves upstream for rapid isolation.',
  'Install two fully independent level transmitters per H2 and O2 separator, using separate tappings, cabling, and power to ensure true redundancy.',
  'Provide fast-response temperature monitoring directly in the hydrogen gas/reaction zone, independent of lye bulk temperature, with hardwired high-temperature trip to initiate rapid isolation and shutdown.',
  'Install a third detonation-proof inline flame arrestor near the electrolyser connection (per the backflash path), sized for design flow, with dP monitoring and defined inspection/cleaning intervals.',
  'Install two H2 LEL detectors at cabinet top (1oo2), with Alarm 10% LEL and Trip 25% LEL; hardwire to F&G/ESD (not BPCS) to auto-start ventilation/purge, isolate power/valves, and annunciate locally/CCR.',
  'Install an independent DC overvoltage isolation relay (set ~1.05–1.10× max design stack voltage, e.g., >320 V) hardwired to a fast DC contactor to isolate within the process-safety time.',
  'Implement double block and bleed valves upstream and downstream of PRS/vessels in the final design, ensuring independent actuation, proper bleed venting to safe location, and compliance with isolation and lock-out/tag-out procedures.',
  'Retrofit hazardous-area–rated forced ventilation (continuous baseline ACH with auto-boost on 10% LEL) hardwired to F&G; at 25% LEL also isolate power/shut H2 valves and annunciate locally/CCR, with fail-safe on loss of power and UPS for fans/controls.',
  'Retrofit a fixed splash shield/deflector with clear view window and drip tray around the filter housing; ensure eyewash/shower within 10 s reach.',
  'Install redundant, independent flow measurement on the lye loop (e.g., mag FT + DP/orifice FT or high-integrity flow switch), with vote-out/validation for alarm and hardwired 1oo2 low-/no-flow trip to shut pumps/isolations within the process-safety time.',
  'Install dual independent online conductivity analyzers on DM feed (with sample conditioning), set Alarm at ~50–70% of OEM limit and Trip/auto-isolate makeup at the limit, hardwired to F&G/ESD and logged to historian with quarterly calibration.',
  'If a conventional BPV is unsuitable, provide a KOH-compatible relief path to a closed/neutralization system (e.g., lined relief valve or rupture disk + burst sensor) sized for worst-case blockage.',
  'Install a surface RTD/thermal switch on the filter housing (and outlet) with Alarm at +8–10 °C over normal and Trip at +15 °C to stop the pump/bypass, hardwired to ESD.',
  'Audit and verify Ex certifications/markings for Hydrogen Group IIC with correct Zone/EPL and T-code/ambient on every item (instruments, glands, JBs, solenoids); replace anything non-compliant.',
  'Fit Ex p (Z/X) purge with pressure/flow monitoring and trip on purge loss; use certified barrier/compound glands and IP66+ door seals, leak-test the cabinet, and capture setpoints/proof-tests in the SRS/Cause-&-Effect.',
  'Specify a detonation-proof arrestor (ISO 16852, IIC; stable/unstable as applicable) at the vent header, sized for worst-case flow/pressure with DP taps and defined inspection/cleaning intervals.',
  'Install automatic N2 backup with check valves and pressure-sensing auto-switchover (on low air pressure), maintain purge flow via regulator/orifice, and hardwire to F&G/ESD to isolate H2, start purge, and alarm/trend the event.',
  'Fit DP transmitters across each dryer (Alarm on rising DP trend; HH = auto tower switchover/trip), add flow-deviation logic (inlet vs outlet FT) and RTDs at bed in/out to flag hotspots/channeling.',
  'Fit 0.01 µm coalescing filters upstream/downstream with DP transmitters (alarm/trip on high ΔP/rate-of-rise) and a hydrocarbon/oil-mist monitor at dryer outlet with auto-divert/recycle on off-spec.',
  'Safeguards actions to implement alongside PRVs: Verify/dispose right - Re-do PRV sizing per worst cases, check inlet ΔP/backpressure limits, and confirm safe disposal capacity',
  'Specify detonation-proof flame arrestor(s) per ISO 16852 (IIC, stable/unstable as applicable) locate per vendor run-up limits (inline near source and/or end-of-line at stack).',
  'Frequent Equipment Failures & Trips: Tripping of blowers, pumps, and cranes due to electrical/control faults and inadequate preventive protocols',
  'Process Upsets from Parameter Instability: Inconsistent process control (e.g., temperature, pressure, flow) in converters, casters, and furnaces causing quality drops and unsafe conditions.',
  'Detection & Monitoring Gaps: Fixed hydrogen leak detectors absent in key locations (valves, manifolds, compressor house); early leak detection requires urgent upgrade.',
  'To initiate predictive monitoring pilots (vibration, thermal imaging) on rotating assets',
  'Launch IOW-based monitoring for corrosion/temperature-sensitive systems',
  'Implement UT checks and thickness trending for high-risk piping and tanks',
  'Develop digital dashboards for BHM, interlocks, and risk registers for real-time monitoring',
  'Emergency egress route and fire fighting equipment shall be kept free from obstruction all the time.',
  'Terrace fire water storage tank of cap 5000 ltrs shall be installed',
  'Fire hose reels and fire hose shall be installed.',
  'Pressurization of lift shaft must be provided. Lift shall be tested and certified by competent person once in every six months. Two way communication system of lift shall be maintained in healthy working condition.',
  'Automatic fire detection and alarm and PA system shall be installed throughout the buildings and maintained in healthy condition.',
  'Suitable window railing shall be provided.',
  'Automatic Fire Suppression Systems shall be provided in the Switchgear Room. Clean agent type Modular Fire Extinguishers or suppression system shall be installed to protect critical switch gears.',
  'Automatic Fire Suppression Systems shall be provided in the Switchgear Room. Dry Chemical Powder type Modular Fire Extinguishers or suppression system or Medium velocity Water Spray system shall be installed to protect critical switch gears.',
  'Combustible scrap materials shall be removed from the Cable cellars.',
  'Portable fire extinguishers shall be installed in the ECR, CR, Cable cellars of HTC-2 ECR.',
  'Such paint cans shall be removed immediately from near the electrical distribution panels.',
  'Railings to be provided at the entrance and hand railing shall be provided at the staircase - Conduct survey on hand rail requirement and develop a road map for implementation including the budget requirement',
  'Such combustible materials shall be removed immediately from near the electrical distribution panels.',
  'Adequate numbers of fire extinguishers (1 number of 10 kgs cap extinguishers for 100 sq. mtrs area with minimum travel distance of 15 mtrs) shall be installed in the Switch gear rooms.',
  'These hydrants posts to be modified or extended up to an accessible location so that these can be used during emergency scenarios. Two nos of 15 mtrs length fire hoses along with a short branch shall be kept in each Hose Box.',
  'Fire extinguishers shall be kept in the extinguisher boxes. Deptt must be informed to the Fire services regarding the extinguisher status.',
  'Fire retardant sealants shall be provided at the entry and exits between Cable cellars and Switchgears.',
  'Fire retardant coatings shall be provided at the entry and exits and at a certain interval to minimize the spread of fire in Cable cellars.',
  'Adequate numbers of fire extinguishers (1 number of 10 kgs cap extinguishers for 100 sq. mtrs area with minimum travel distance of 15 mtrs) shall be installed in the HTC area.',
  'Two nos of 15 mtrs length fire hoses along with a short branch shall be kept in each Hose Box. Hose box glasses and one window shall be re-fitted.',
  'The FDA system shall be kept in healthy condition - Conduct a RCFA and implement the recommendations',
  'Automatic Fire Suppression Systems shall be provided in the Switchgear Room. Clean agent type Modular Fire Extinguishers or suppression system shall be installed to protect critical switch gears.',
  'Fire retardant coatings shall be provided at the entry and exits and at a certain interval to minimize the spread of fire in Cable cellars.',
  'Fire retardant sealants shall be provided at the entry and exits between Cable cellars and Switchgears.',
  'The electrical DB need to be covered properly.',
  'Cable trays to be covered and sealed to protect from any external fires.',
  'Transformer yards shall be free from any obstructions for easy access of emergency equipment.',
  'Combustible materials shall be removed from that area.',
  'Fire detection and alarm system shall be installed in the building.',
  'Minimum Fire safety requirements shall be complied.',
  'Self illuminated "EXIT" and "EMERGENCY EXIT" signage shall be displayed in the building.',
  'Travel distance from any remote point of the Shramaveer palace to the Exit door shall not be more than 22.5 mtrs - Develop a work plan with budgetary estimate and implement the requirement',
  'Fire doors of minimum of 2 hours rating shall be fitted. Exit doors must be opened towards outside of the building. Panic bars shall be fitted in doors.',
  'Management shall consider the compartmentation - Conduct technical study and come out with road map for implementation including the budget estimate',
  'Fire extinguishers shall be kept near the entrances and shall be visible.',
  'Accommodation area shall not be used as storage of combustible materials.',
  'Adequate numbers of kitchens shall be allotted so that people can not use open chullas for cooking.',
  'Lights to be fitted in each kitchen.',
  'Walkways between the beds shall be free from any obstructions. Management shall consider the required Occupant load per person for occupants in shramik vihars.',
  'Proper arrangements shall be made for ventilation - Come out with budgetary quote and implement with road map',
  'There is need to renovate those Electrical fittings and accessories as most of the fans are not working.',
  'Housekeeping of those rooms are not being carried out. Unused materials shall be removed from the rooms.',
  'Provisions shall be made for protecting those rooms or beds for dust accumulation - Come out with the budgetary estimate for technical study and implement the recommendation with road map',
  'Kitchen shall be provided at different location near to the shramik vihar - Come out with the budgetary estimate for technical study and implement the recommendation with road map',
  'Adequate numbers of kitchens shall be provided away from the rooms - Come out with the budgetary estimate for technical study and implement the recommendation with road map',
  'Height of the hydrant posts including isolation valves need to be extended - Come out with the budgetary estimate for technical study and implement the recommendation with road map',
  'Hand wheels need to be fitted on isolation valves of the Hydrant posts - Come out with the budgetary estimate for technical study and implement the recommendation with road map',
  'Periodic Inspection needs to be conducted frequently',
  'Water leakage from the hydrant to be arrested. Fire hydrant valve to be installed. Monitor height to be reduced. Hose box with hose and nozzle to be installed.',
  'Unauthorized tapping for non emergency use of fire water shall be removed. Monitor shall be suitably positioned for effective use.',
  'Hose box with hose and nozzle to be installed near to each hydrant point - Come out with the budgetary estimate for technical study and implement the recommendation with road map',
  'Unauthorized tapping shall be removed from hydrant valve. 2 nos of hose & 1 nozzle shall be kept inside each hose box.',
  'Fire water riser isolation valve shall be kept in open condition all the time.',
  'Panel to be installed in a 24X7 manned location. All active fire alarm to be investigated and reset.',
  'Plastic tarpaulin cover shall be removed and suitable arrangement shall be made against weather protection.',
  'Misuse of fire water and equipment shall be strictly restricted. Hydrant point shall be removed from the road.',
  'Tapping for non emergency use shall be removed. Standard and suitable fire fighting equipment shall be installed.',
  'Fire hydrant valve shall be installed in place of monitor and isolation valve shall be kept in open condition. MVWS shall be installed in all cable cellar of sub stations.',
  'Good housekeeping shall be maintained. Nitrogen injection system shall be maintained in healthy condition.',
  'Fire fighting equipment shall be maintained in healthy condition.',
  'Good housekeeping shall be maintained and combustible scrap shall be safely disposed.',
  'Automatic Fire Suppression Systems shall be provided in the Switchgear Room.',
  'Automatic Fire Suppression Systems shall be provided in the Cable Cellars Oxygen Plant.',
  'Fire retardant coatings shall be provided on the cables.',
  'Such combustible materials need to be removed from the Switch Gear Room.',
  'Vehicles shall not be parked in front of Transformers.',
  'Access to be provided. Hose box must be fitted beside each hydrant posts. Two nos of 15 mtrs length fire hoses along with a short branch shall be kept in each Hose Box.',
  'Isolation Valves must be provided in all hydrant posts (before landing valves) so that landing valves can be checked without shutting down the Main header/Fire water line.',
  'Water must be removed and water seepage shall be stopped - RCFA to be conducted for water seepage and its recommendations to be implemented',
  'Hose box shall be fitted beside each hydrant post.',
  'Oil filled drums shall be removed from there.',
  'Combustible scrap materials need to be removed from there in priority.',
  'Two wheeler to be parked in designated parking area - Conduct a survey and provision for two wheeler parking needs to be done.',
  'Water spray line painting to be ensured.',
  'Fire extinguishers stand shall be painted & conspicuously placed.',
  'Green vegetation shall be cleaned.',
  'Housekeeping and access to be arranged across all the DV area. Hose to be provided.',
  'Painting & marking to be ensured.',
  'Spray system shall be kept in healthy condition - Conduct RCFA and recommendation shall be implemented.',
  'Faulty LHS cable shall be replaced and system to be reset - Conduct RCFA and recommendation shall be implemented.',
  'New line to be installed - Gap assessment to be done and come out with budget estimate and implementation road map.',
  'Valve shall be maintained in healthy condition without leakage - Conduct RCFA and recommendation shall be implemented.',
  'Vegetation shall be removed and suitable platform shall be made around the DV station. Deluge valve shall always be maintained in healthy condition.',
  'Suitable platform shall be made around the DV station. Deluge valve & hydrant shall always be maintained in healthy condition.',
  'Inergen & CO2 flooding system shall be maintained in healthy working condition and periodic testing/checking shall be done.',
  'Fire fighting equipment shall be maintained in healthy condition. Deluge valve shall be kept in auto operation mode.',
  'Emergency fire fighting equipment shall be maintained in healthy and working condition. Scheduled PM shall be done.',
  'Automatic Fire Suppression Systems shall be provided in the Switchgear Room. Modular Fire Extinguishers shall be installed to protect critical switch gears, MCPs.',
  'Plastic covers shall be removed from the nozzles. The DV System needs to be commissioned in priority.',
  'Accumulated iron dusts to be cleaned and Greasing of all gate valves to be conducted.',
  'Self illuminated "EXIT" and "EMERGENCY EXIT" signage need to be displayed in the building.',
  'Scrap materials shall be removed from the Cable cellars.',
  'Nozzle to be fitted in the Hose reel, 2 lengths (15 mtrs) of fire hoses and a nozzle to be kept in the Hose box.',
  'The DV System needs to be commissioned in priority.',
  'Need to be re-checked by the AMC vendor in priority.',
  'FR Coatings shall be provided on cables at a defined interval. Sealant must be provided at the entry and exit of the cables.',
  '02 nos of 15 mtrs length hose and a nozzle to be kept in each hose box.',
  'New hose boxes to be installed in place of those damaged fire hose boxes. Two nos of 15 mtrs length fire hoses along with a short branch shall be kept in each Hose Box.',
  'Periodic inspection, checking and greasing of gate valves need to be done in priority.',
  'Damaged fire hoses shall not be used - Damaged fire hose needs to be removed after site survey.',
  'Iron fines must be cleaned frequently - RCFA for dust generation needs to be conducted.',
  'The MOEFA system shall be maintained in healthy working condition and periodic testing/checking shall be carried out.',
  'PA Systems need to be made functional and periodic inspection and checking of the systems must be carried out.',
  'Checking, Inspection and Testing of Fire water pumps are not being carried out. Pumps are kept in Manual mode.',
  'Periodic inspection, checking and testing of Fire water pumps, Hose reels and hydrants shall be carried out.',
  'Floor Plan or Evacuation Plan posters are not displayed in the building. Floor Numbers are not mentioned in front of the Lift landings or staircase landings.',
  'The corridors of every floor of the building are to be kept free of obstruction at all times.',
  'The cabinets/boxes meant for fire equipment should not be used for storing any other material.',
  'Periodic testing of the FB inlets to be done. Pruning of branches/lateral extension of trees to be done at periodic intervals.',
  'Combustible wastes/scraps should be removed from the basement area.',
  'MVWS shall be fitted on the conveyors. Risers consisting escape hydrants, hose boxes and nozzles shall be fitted at the intermediate staircases of the Conveyor Galleries.',
  'Fixed fire protection systems need to be checked during every shutdown periods and records to be maintained by the Deptt.',
  'Risers and Jet/spray line and valves must be marked. Soil around the isolation valve shall be removed.',
  'Standard hydrant posts consisting 63 mm dia landing valve, 80 mm dia isolation valve and "C" class pipe shall be fitted at truck tippler area.',
  'Isolation valve shall be kept in opened condition always. Accumulated fines must be cleaned frequently.',
  'The riser shall be connected to the hydrant line of the Sinter Conveyors at nearest JH.',
  'Fire hoses shall not be used for different purposes other than fire. Healthy hoses need to be kept in boxes.',
  'Such unused oils shall be removed from the junction houses immediately and to be sent for disposal.',
  'Such unused oils and scraps shall be removed from the junction houses immediately and to be sent for disposal.',
  'Staircase needs to be extended up to the Gallery of OFC-2. Steps, Hand railings to be provided.',
  'Auto fire suppression system shall be installed in the drive room to protect Critical drives/switchgears. Modular Fire Extinguishers can also be installed as an alternate.',
  'FDA system shall be kept in healthy condition - Conduct RCFA and come out with budget estimate and implementation road map.',
  'Sealant shall be provided around the cables at the entry and exits of the Cable Cellars.',
  'Unused materials shall be removed beside the staircase.',
  'Parking of vehicles in front of the entrances of HTSS building shall be restricted.',
  'Foam Pourers of the Benzol tanks need to be checked frequently to ensure its healthiness and records to be maintained accordingly.',
  'Painting of the Fire water line needs to be carried out frequently.',
  'Mentioned sprinkler system shall be checked monthly and records to be maintained.',
  'Emergency equipment shall not be obstructed. Scrap materials need to be removed from that area.',
  'Tower Monitors need to be installed beside the Ammonia Scrubber.',
  'Monitors need to be fitted on those points and flow of water to be checked.',
  'Such portable foam monitors need to be checked to ensure its healthiness frequently.',
  'A distinct register to be made for the running, checking and operation of Foam systems and records to be maintained accordingly.',
  'Height of the isolation valve needs to be increased. Height of the Water Monitor needs to be reduced.',
  'Periodic inspection, checking and greasing of isolation valves need to be carried out frequently.',
  'That gate to be marked as entry into the Tar Tank storage area. Covers on the drains need to be placed.',
  'Painting of the fire hut/stands needs to be done.',
  'All hydrant posts, Fire water lines shall be painted with fire red or post office red colour.',
  'HVWS system must be installed on transformers.',
  'Automatic Fire suppression system must be installed in cable cellar and Switchgear rooms.',
  'Combustible scrap materials must be removed near Transformers.',
  'Access to be provided for the movement of Fire vehicles.',
  'Fire suppression system shall be installed to protect Cables in the cable gallery.',
  'Yard Hydrants shall be provided.',
  'Project works shall be carried out after ensured clearance from the Central Electrical at those locations beside Cable Gallery.',
  'Portable Fire Extinguishers shall be installed in priority. Risers shall be installed at each floor of Screen Building. Medium Velocity Spray system shall be installed in the conveyor gallery to protect conveyors.',
  'Portable Fire Extinguishers shall be installed in priority. Risers shall be installed at each floor of Crusher Building. Medium Velocity Spray system shall be installed in the conveyor gallery to protect conveyors.',
  'Portable Fire Extinguishers shall be installed in priority. Risers shall be installed at each floor of Hopper Building. Medium Velocity Spray system shall be installed in the conveyor gallery to protect conveyors.',
  'Access to reach the Crusher Building shall be cleared. Scrap materials need to be removed from that area.',
  'Guards shall be provided around the moving machinery and equipment at Crusher building to avoid man machine interception.',
  'Systems shall be developed for spillages of fines around the conveyors and idlers. Coal fines must be cleaned on daily basis.',
  'Need to control the spillages in priority and workers to be engaged for daily cleaning of such coal heaps.',
  'A distinct register to be made for the running, checking and operation of Foam systems and records to be maintained accordingly.',
  'Fire hydrants, Hose reels (Riser Systems), and Medium Velocity Water Spray systems to be installed in JH-1 and JH-2 of the BOF project.',
  'The Riser System to be installed in the main Electrical/Control Room Building of BOF.',
  'Some Switch Gears have already been charged in the Control Room Building. But Portable Fire extinguishers have not been installed.',
  'Installation of Fire Detection and Alarm Systems is going on at the Control Room Building. Smoke detectors are not installed in the false ceiling.',
  'An Automatic Fire suppression system shall be installed to protect critical equipment/rooms such as Switchgears, Hydraulic pumps, Cable cellars, gas manifolds and etc.',
  'Adequate numbers of portable fire extinguishers shall be procured and installed at all locations of BOFs of SMS-2.',
  'High-Velocity Water spray systems or Nitrogen Injection Fire Protection Systems shall be installed on 10 MVA and above rated Transformers.',
  'Auto fire suppression system shall be installed in the Cable cellar rooms to protect Cables. Modular Fire Extinguishers can also be installed as an alternate.',
  'The existing NIFPS needs to be checked and maintained and records to be maintained accordingly. Yard hydrants and Water cum foam monitors shall be provided near the Transformers as a secondary protection system.',
  'FR Coatings shall be provided around the cables.',
  '"Emergency Exit" doors shall not be locked. Self illuminated "EXIT" and "Emergency Exit" signages need to be installed there.',
  'Auto fire suppression system shall be installed in the drive room to protect Critical drives/switchgears. Modular Fire Extinguishers can also be installed as an alternate.',
  'Fire doors having a minimum of 2 hours fire rating shall be fitted in the ECR building.',
  {/*'Fire hydrants, hosereels, hose boxes shall be installed in the Junction Houses or TTDs.',
  'Water Spray/Jet systems should be installed in the Conveyor Gallery.',
  'Risers (Hydrants, Hose boxes) shall be extended up to the Conveyor gallery at each staircase access.',
  'Proper access to be provided for the movement of Fire/Emergency vehicles - Technical study for fire fighting vehicle access to be done.',
  'Linear Heat Sensing (LHS) cables should be installed throughout the conveyor for early detection of the fire.',
  'Portable Fire extinguishers need to be installed in each JH.',
  'Hydrant line to be connected with the main Header.',
  'Air release valve to be connected - Conduct RCFA.',
  'Portable Fire Extinguishers need to be installed on each elevation of the Furnace Building.',
  'Water Spray systems need to be installed to protect feeding conveyor.',
  'Landing valves are not fitted in the Feeding Conveyor Gallery.',
  'Risers to be fitted.',
  'Modular Fire Extinguishers for ECR Buildings.',
  'FDA System to be started on priority.',
  'Risers in the ECR Buildings (To be included in the design).',
  'Risers in Junction Houses.',
  'Water Spray System in the Conveyor Galleries.',
  'Yard Hydrants needs to be installed at prominent locations.',
  'Fire Detection and Alarm (FDA) System (Smoke detectors, MCPs, Hooters etc) shall be installed in all ECRs.',
  'Linear Heat Sensing Cables or an Infrared detection system shall be installed throughout the Pipe conveyor and TPs/JHs.',
  'Yard Hydrants shall be installed at prominent locations beside the JHs/TPs.',
  'Fire Escape Hydrants (along with hose boxes, fire hoses) shall be installed inside the JHs/TPs and landing platforms of ECR Buildings.',
  'Automatic Fire Suppression System (Medium Velocity or High velocity Water Spray System) shall be installed throughout the conveyor.',
  'A Suitable Fire suppression system shall be installed in the cable cellars and MCC rooms.',
  'Portable Fire Extinguishers shall be installed in all ECR buildings and Junction Houses.',
  'Healthiness of the FDA system shall be ensured for early detection of the fire or smoke in Electrical rooms and Control rooms.',
  'All electrical fittings shall be flameproof inside the Pipe cellar.',
  'Isolation valve needs to be replaced/repaired. Landing valve shall be fitted properly. Hand wheel must be fitted on landing valve.',
  'Combustible scrap materials need to be removed from there.',
  'Outlet of the valve shall be fitted downwards and a minimum 3 feet distance shall be maintained from the floor level.',
  'Spillage of oils from the drives need to be controlled and housekeeping to be conducted frequently.',
  'Every fire incident shall be reported. Emptied fire extinguishers shall be refilled immediately and 30% of the total stocks of fire shall be kept standby in the Barmill.',
  'Automatic Fire suppression system shall be installed to protect critical equipment at Hyd. Cellar. Emptied drums shall be removed from there frequently.',
  'Unwanted materials shall be removed from the Roll shop.',
  'Combustible scrap materials shall be removed from the Roll Shop. Old and unused rollers need to be removed and sold out.',
  'Unwanted materials shall be removed from the Pump House. The walkway between the pumps shall be cleared from any obstruction.',
  'A minimum of 04 nos of fire extinguishers shall be kept in the Pump House.',
  'All canteen staff must receive comprehensive fire safety training, including fire extinguisher use, evacuation procedures, and hazard identification.',
  'Install and maintain a functioning fire alarm system throughout the kitchen.',
  'Ensure proper types and quantities of fire extinguishers are readily available in the kitchen, based on potential fire risks. Train staff on proper extinguisher use.',
  'Install a properly designed and maintained exhaust system to effectively remove heat, smoke, and grease build-up from the kitchen environment.',
  'Implement a strict schedule for cleaning and maintaining the exhaust system. This includes removing grease build-up from filters, fans, and ducts at regular intervals.',
  'Maintain clear access to all exits and fire safety equipment. Store flammable materials (cleaning supplies, oils, etc.) safely in designated, approved containers away from heat sources.',
  'Implement a regular deep cleaning schedule for kitchen equipment, exhaust systems, and filters to remove grease build-up - a major fire hazard.',
  'Regularly inspect and maintain all electrical equipment in the kitchen – faulty wiring is a common fire cause.',
  'Store LPG cylinders in a well-ventilated area outside the kitchen, away from heat sources and direct sunlight. Train staff on proper handling and leak detection procedures.',
  'Consider installing additional fire suppression systems like automatic hoods or sprinkler systems for high-risk burner areas.',
  'Ensure fire doors are self-closing and in good working order, preventing fire spread from the kitchen to other areas.',
  'Clearly display fire escape route signs and emergency evacuation procedures throughout the kitchen. Conduct practice evacuation drills to ensure staff familiarity.',
  'Maintain a clean and organized kitchen environment to minimize potential fire hazards. Regularly dispose of waste and food scraps in designated bins.',
  'Consider having fire blankets readily accessible for small pan fires as an alternative to fire extinguishers.',
  'Fire Detection and Alarm Systems: Smoke detectors, Heat Detectors, MCPs, Hooters, RIs installed in prominent locations. There is a need to monitor/record/attend to all alarms by a dedicated team round the clock.',
  'Automatic Fire Suppression System: Automatic Sprinkler System fitted in the Hotel and covered guest, service and other areas. Protective covers of sprinkler QBDs need to be removed from all locations.',
  'Fire Hydrant and Hose Reel System: Fire Water Pumps, Yard Hydrants, Escape Hydrants, Hose reels have been installed at prominent locations.',
  'Portable Fire Extinguishers: Portable fire extinguishers are kept on the floor in front of Fire Cabinets. Adequate numbers of portable fire extinguishers need to be fixed on the wall or kept on stands/boxes.',
  'A Fire/Emergency Command/Control Center shall be established dedicated to Jay Bhoomi Retreat.',
  'A dedicated team comprising qualified fire manpower shall be deployed in the Emergency Control Center of Jay Bhoomi for monitoring Fire Alarms and other emergency services.',
  'Breathing Apparatus Sets, Foldable Stretchers, Firstaid Boxes shall be kept in the Jay Bhoomi.',
  'Evacuation Plans are displayed in each guest room but not in the common areas/corridors.',
  'Informative write-ups (Location guides) are pasted on the corridors but are not clearly visible. Floor Numbers are not mentioned in the Lift and Staircase corridor.',
  'Emergency Lighting and Accessible Exits: Provided at each floor of the Building but the arrow and stairways pictures are missing in the signages.',
  'Emergency Evacuation Plan: Not evidenced. Need to be made.',
  'PA System: Installed in the Building. Periodic checking of the PA Systems shall be carried out.',
  'Trainings on Emergency Evacuation Plan: Not evidenced. All staff must be trained on emergency procedures, the use of Fire safety equipment installed in the Hotel, and how to assist guests during emergencies.',
  'Fire Drills: Not evidenced. All staff must participate in regular fire drills to practice emergency response and evacuation protocols.',
  'First Aid Training: Hotel Service Staff must provide immediate care for guests and colleagues during medical emergencies.',
  'Fire Safety Certificate from Odisha Fire Services: Recommendation Certificate is available.',
  'Fire Lift: A dedicated lift for Emergencies as per NBC-2016.',
  'Assembly points should be designated at the ground floor occupants of each floor.',
  'Automatic Smoke Ventilation: Provided.',
  'Compartmentalization: Provided but needs to check the cable routes from the Service rooms, Pump rooms.',
  'Eliminate manual water sprinkling on hot sinter by redesigning the process so that cooling is carried out without human presence near the conveyor.',
  'Substitute manual valve operation with an automatic or semi-automatic water sprinkling (auto-mode) system having controlled flow and fail-safe features.',
  'Install steam exhaust / forced ventilation to prevent steam accumulation.',
  'Provide physical barriers and exclusion zones to keep personnel away from the cooling area.',
  'Improve tunnel design with emergency exits, lighting, and visibility.',
  'Provide CCTV or remote monitoring to supervise the operation.',
  'Implement strict housekeeping controls to ensure clear walkways, proper drainage of excess water, and removal of obstructions that restrict safe movement or escape.',
  'Carry out risk assessment for hot sinter cooling and treat the tunnel as a high-risk / confined area.',
  'Develop and implement a clear SOP defining auto/manual operation, communication protocol, safe positioning, and emergency response.',
  'Implement a standard confirm-and-acknowledge communication system before water application.',
  'Provide task-specific training, competency authorization, and strengthen supervision.',
  'Define, provide and strictly enforce use of heat- and steam-resistant PPE including gloves, protective clothing, and face/eye protection.',
  'Initiate the safe rigging certification process through skill center.',
  'Initiate the PTW certification process through skill center.',
  'Preventive Maintenance of all Crane to be mapped with SAP system by CMED.',
  'Initiate the crane operator certification process through skill center.',
  'Ensure thorough investigation of Tier-3 incidents with proper RCA.',
  'Restriction of movement of bicycles, as these are not visible due to dense fog in morning.',
  'Each activity starting from entry of the trailer inside the factory premises to dispatch after TMT bar loading, shall be defined and Safe procedure shall be implemented like FIFO.',
  'The SOP for TMT end capping job shall be updated and implemented with prior training to helpers, trailer drivers and supervisors.',
  'Parking of trailer and pre end capping activities shall be done in designated area with proper display of SOP and Cautionary boards.',
  'The railway line area near the parking area shall be properly barricaded and cautionary boards to be displayed for awareness of workers working nearby.',
  'A dedicated workstation area to be developed for the pre end capping activity with adequate sitting arrangement and basic amenities, public address system, display of vehicle numbering system, traffic light system and CCTV surveillance.',
  'A dedicated SOP for FIFO right from parking area to gate entry and exit to be developed and communicated to all stakeholders at the earliest.',
  'A designated parking area (buffer zone) in each department to be developed along with basic amenities in and out separate entries. The dedicated parking area shall be installed with AI cameras for detection of parking/wrong parking.',
  'All heavy vehicles to be incorporated with reverse camera, standard side under protection guard (SUPD), standard rear under protection guard (RUPD).',
  'SOP to be updated including the full cycle movement of the vehicle (in to out). The SOP shall clearly define the role of the driver for handing over/takeover of the vehicle ignition key and wheel choke placing/removal.',
  'Crew staff shall be trained on the updated SOP and a monthly audit by section in-charge and safety office for effective implementation.',
  'A survey for man-machine segregation with dedicated pedestrian walkways in roads across the plants shall be carried out and prepare the action plan for implementation.',
  'Defensive Driving training in the form of video needs to be imparted for all the drivers with online assessment (in-bound and out-bound) at Transport Nagar.',
  'Vehicle check list points at Transport Nagar shall be carried out under camera surveillance for full compliance.',
  'Activity based traffic management plan to be developed.',
  'A hard copy of delivery order to be made digital and implemented.',
  'All the roads shall be installed with AI cameras for behavioral movement after gap analysis.',
  'Central traffic control centre (CTCC) shall be developed along with dedicated manpower to monitor the traffic movement, violations and counselling by traffic marshals equipped with dedicated vehicle round the clock.',
  'Action pending from R&T survey report shall be completed on priority.',
  'R&T SOP shall be developed and communication for implementation.',
  'A Dust Separation and Dust Exhauster System is to be installed in the Slag Yard to effectively control and manage airborne particulate matter.',
  'Auto Coupling system in SMS1 (Pending since long).',
  'Ensure closure of door on the tapping side of the converter during tapping activity.',
  'FR suits, hot-slag resistant footwear for KRESS operators.',
  'Provide drum tilter / mechanical handling arrangement for tilting of drums.',
  'Structure Stability issue in Slag Processing Plant.' */}
];

// Generate 200 records
export const populateDemoData = async (saveRecommendation: Function) => {
  const demoRecords = [];

  // Start date for recommendations (Jan 2024 to March 2026)
  const startDate = new Date(2024, 0, 1);
  const endDate = new Date(2026, 2, 31);

  for (let i = 1; i <= 500; i++) {
    const source = sourceOptions[Math.floor(Math.random() * sourceOptions.length)];
    const plantName = plantOptions[Math.floor(Math.random() * plantOptions.length)];
    const location = locationOptions[Math.floor(Math.random() * locationOptions.length)];
    const section = sectionOptions[Math.floor(Math.random() * sectionOptions.length)];
    const equipmentType = equipmentTypes[Math.floor(Math.random() * equipmentTypes.length)];
    const status = getRandomStatus();
    const eligible = getRandomEligibility();
    const dateOfRec = getRandomDate(startDate, endDate);
    const targetDate = new Date(dateOfRec);
    targetDate.setMonth(targetDate.getMonth() + Math.floor(Math.random() * 12) + 1);
    const actualDate = status === 'Implemented' ? new Date(targetDate) : null;
    if (actualDate) {
      actualDate.setDate(actualDate.getDate() + Math.floor(Math.random() * 30));
    }
    
    const initialRisk = Math.floor(Math.random() * 15) + 5;
    const finalRisk = Math.floor(Math.random() * (initialRisk - 1)) + 1;
    const estimatedCostVal = Math.floor(Math.random() * 500) / 10;
    
    // Get recommendation description based on index, cycling through the array
    const descriptionIndex = (i - 1) % recommendationDescriptions.length;
    
    demoRecords.push({
      source: source,
      plantName: plantName,
      location: location,
      section: section,
      equipmentId: `EQ-${String(1000 + i).slice(-4)}`,
      equipmentType: equipmentType,
      equipmentDescription: `${equipmentType} System ${String(i).padStart(3, '0')}`,
      recommendationDescription: recommendationDescriptions[descriptionIndex],
      recommendationType: ['risk_reduction', 'safety_assurance', 'quality_improvement', 'productivity_improvement'][Math.floor(Math.random() * 4)],
      consequenceSelectionType: ['people', 'asset', 'environment', 'financial'][Math.floor(Math.random() * 4)],
      initialConsequence: String(Math.floor(Math.random() * 5) + 1),
      initialLikelihood: String(Math.floor(Math.random() * 5) + 1),
      initialRiskScore: String(initialRisk),
      injuryPotential: ['none', 'firstaid', 'mtc', 'lti', 'fatal', 'multiplefatal'][Math.floor(Math.random() * 6)],
      assetRepairCost: Math.floor(Math.random() * 5000000),
      productionLossPerDay: Math.floor(Math.random() * 500000),
      potentialRiskImpactMin: parseFloat((Math.random() * 5).toFixed(1)),
      potentialRiskImpactMedium: parseFloat((Math.random() * 10).toFixed(1)),
      potentialRiskImpactMax: parseFloat((Math.random() * 20).toFixed(1)),
      finalConsequence: String(Math.floor(Math.random() * 3) + 1),
      finalLikelihood: String(Math.floor(Math.random() * 3) + 1),
      finalRiskScore: String(finalRisk),
      benefitOfImplementation: `Expected annual savings of ₹${Math.floor(Math.random() * 500) + 50} Lakhs with improved safety and reliability`,
      estimatedCost: estimatedCostVal,
      shutdownRequirement: Math.random() > 0.7 ? 'Yes' : 'No',
      dateOfRecommendation: dateOfRec,
      targetImplementationDate: targetDate,
      actualImplementationDate: actualDate,
      ageOfRecommendation: String(Math.floor((new Date().getTime() - dateOfRec.getTime()) / (1000 * 60 * 60 * 24))),
      benefitAnalysisTargetDate: targetDate ? new Date(targetDate.getTime() + 60 * 24 * 60 * 60 * 1000) : null,
      numberOfOverdueDays: status === 'Open' && new Date() > targetDate ? String(Math.floor((new Date().getTime() - targetDate.getTime()) / (1000 * 60 * 60 * 24))) : '0',
      recommendationInitiatedBy: ['ED Incharge', 'Plant Manager', 'Safety Head', 'Quality Head', 'Maintenance Head'][Math.floor(Math.random() * 5)],
      discussedWithHOD: Math.random() > 0.3 ? 'Yes' : 'No',
      dateOfDiscussion: new Date(dateOfRec.getTime() + 5 * 24 * 60 * 60 * 1000),
      responsiblePersonForClosure: ['Maintenance Manager', 'Operations Head', 'Project Manager', 'Safety Manager'][Math.floor(Math.random() * 4)],
      status: status,
      reasonForRejection: status === 'Rejected' ? 'ROI not meeting minimum requirements, budget constraints' : '',
      rejectedBy: status === 'Rejected' ? 'Steering Committee' : '',
      eligibleForRecommendation: eligible,
      remarks: status === 'Open' ? 'Awaiting approval and budget allocation' : status === 'In-Progress' ? 'Implementation in progress, tracking ongoing' : status === 'Implemented' ? 'Successfully implemented, benefits being monitored' : '',
      changeHistory: [],
    });
  }

  // Save all records
  for (const record of demoRecords) {
    await saveRecommendation(record);
  }
  
  console.log(`Successfully seeded ${demoRecords.length} demo recommendations`);
};