// utils/demoData.ts

export const populateDemoData = async (saveRecommendation: Function) => {
  const demoRecords = [
    {
      // Row 1
      source: 'Apex',
      plantName: 'All',
      location: 'Angul',
      section: '',
      equipmentId: 'NA',
      equipmentType: 'NA',
      equipmentDescription: 'NA',
      recommendationDescription:
        'Centralized ARC to be done for structural integrity and all the requirements to be collated for the same and all technical requirements and documentation to be collated centrally for consistency and traceability.',
      recommendationType: 'safety_assurance',
      consequenceSelectionType: 'people',
      initialConsequence: '5',
      initialLikelihood: '4',
      initialRiskScore: '20',
      injuryPotential: 'multiplefatal',
      assetRepairCost: null,
      productionLossPerDay: null,
      potentialRiskImpactMin: null,
      potentialRiskImpactMedium: null,
      potentialRiskImpactMax: null,
      finalConsequence: '',
      finalLikelihood: '',
      finalRiskScore: '0',
      benefitOfImplementation: '',
      estimatedCost: 0,
      shutdownRequirement: '',
      dateOfRecommendation: null,
      targetImplementationDate: null,
      actualImplementationDate: null,
      ageOfRecommendation: '',
      benefitAnalysisTargetDate: null,
      numberOfOverdueDays: '',
      recommendationInitiatedBy: '',
      discussedWithHOD: '',
      dateOfDiscussion: null,
      responsiblePersonForClosure: '',
      status: 'Open',
      reasonForRejection: '',
      rejectedBy: '',
      eligibleForRecommendation: '',
      remarks: '',
      changeHistory: [],
    },
    {
      // Row 2
      source: 'Apex',
      plantName: 'All',
      location: 'Angul',
      section: '',
      equipmentId: 'NA',
      equipmentType: 'NA',
      equipmentDescription: 'NA',
      recommendationDescription:
        'PM instructed to centrally collate plant-wide scaffolding data, including total tonnage requirements, total cubic meter area required so that this data will support planning, cost control, and for central ARC.',
      recommendationType: 'safety_assurance',
      consequenceSelectionType: 'people',
      initialConsequence: '5',
      initialLikelihood: '4',
      initialRiskScore: '20',
      injuryPotential: 'multiplefatal',
      assetRepairCost: null,
      productionLossPerDay: null,
      potentialRiskImpactMin: null,
      potentialRiskImpactMedium: null,
      potentialRiskImpactMax: null,
      finalConsequence: '',
      finalLikelihood: '',
      finalRiskScore: '0',
      benefitOfImplementation: '',
      estimatedCost: 0,
      shutdownRequirement: '',
      dateOfRecommendation: null,
      targetImplementationDate: null,
      actualImplementationDate: null,
      ageOfRecommendation: '',
      benefitAnalysisTargetDate: null,
      numberOfOverdueDays: '',
      recommendationInitiatedBy: '',
      discussedWithHOD: '',
      dateOfDiscussion: null,
      responsiblePersonForClosure: '',
      status: 'Open',
      reasonForRejection: '',
      rejectedBy: '',
      eligibleForRecommendation: '',
      remarks: '',
      changeHistory: [],
    },
    {
      // Row 3
      source: 'BHM',
      plantName: '1200 O2',
      location: 'Angul',
      section: '',
      equipmentId: 'NA',
      equipmentType: 'NA',
      equipmentDescription: 'NA',
      recommendationDescription:
        'Additional CO2 detector to be installed in adsorber outlet to ensure accurate reading.',
      recommendationType: 'preventive',
      consequenceSelectionType: 'people',
      initialConsequence: '5',
      initialLikelihood: '4',
      initialRiskScore: '20',
      injuryPotential: '',
      assetRepairCost: null,
      productionLossPerDay: null,
      potentialRiskImpactMin: '98',
      potentialRiskImpactMedium: null,
      potentialRiskImpactMax: null,
      finalConsequence: '5',
      finalLikelihood: '2',
      finalRiskScore: '10',
      benefitOfImplementation: '0',
      estimatedCost: 1,
      shutdownRequirement: 'no',
      dateOfRecommendation: new Date('2025-08-08').toISOString(),
      targetImplementationDate: new Date('2026-07-08').toISOString(),
      actualImplementationDate: null,
      ageOfRecommendation: '236',
      benefitAnalysisTargetDate: null,
      numberOfOverdueDays: '',
      recommendationInitiatedBy: 'ED Incharge',
      discussedWithHOD: '',
      dateOfDiscussion: null,
      responsiblePersonForClosure: '',
      status: 'Open',
      reasonForRejection: '',
      rejectedBy: '',
      eligibleForRecommendation: 'yes',
      remarks: '',
      changeHistory: [],
    },
    {
      // Row 4
      source: 'BHM',
      plantName: '1200 O2',
      location: 'Angul',
      section: '',
      equipmentId: 'NA',
      equipmentType: 'NA',
      equipmentDescription: 'NA',
      recommendationDescription:
        'CO2 analyser calibration frequency to be increased from 4 months to shorter duration & CO2 analyser accuracy of reading should be periodically compared with quality control sampling.',
      recommendationType: 'preventive',
      consequenceSelectionType: 'people',
      initialConsequence: '5',
      initialLikelihood: '4',
      initialRiskScore: '20',
      injuryPotential: '',
      assetRepairCost: null,
      productionLossPerDay: null,
      potentialRiskImpactMin: null,
      potentialRiskImpactMedium: null,
      potentialRiskImpactMax: null,
      finalConsequence: '',
      finalLikelihood: '',
      finalRiskScore: '0',
      benefitOfImplementation: '',
      estimatedCost: 0,
      shutdownRequirement: '',
      dateOfRecommendation: null,
      targetImplementationDate: null,
      actualImplementationDate: null,
      ageOfRecommendation: '',
      benefitAnalysisTargetDate: null,
      numberOfOverdueDays: '',
      recommendationInitiatedBy: 'ED Incharge',
      discussedWithHOD: '',
      dateOfDiscussion: null,
      responsiblePersonForClosure: '',
      status: 'Open',
      reasonForRejection: '',
      rejectedBy: '',
      eligibleForRecommendation: 'no',
      remarks: '',
      changeHistory: [],
    },
    {
      // Row 5
      source: 'BHM',
      plantName: '1200 O2',
      location: 'Angul',
      section: '',
      equipmentId: 'NA',
      equipmentType: 'NA',
      equipmentDescription: 'NA',
      recommendationDescription:
        'Field air intake CO2 analyser to initiate an alarm for the operator to take action on high CO2 detection.',
      recommendationType: 'preventive',
      consequenceSelectionType: 'people',
      initialConsequence: '5',
      initialLikelihood: '4',
      initialRiskScore: '20',
      injuryPotential: '',
      assetRepairCost: null,
      productionLossPerDay: null,
      potentialRiskImpactMin: null,
      potentialRiskImpactMedium: null,
      potentialRiskImpactMax: null,
      finalConsequence: '',
      finalLikelihood: '',
      finalRiskScore: '0',
      benefitOfImplementation: '',
      estimatedCost: 0,
      shutdownRequirement: '',
      dateOfRecommendation: null,
      targetImplementationDate: null,
      actualImplementationDate: null,
      ageOfRecommendation: '',
      benefitAnalysisTargetDate: null,
      numberOfOverdueDays: '',
      recommendationInitiatedBy: 'ED Incharge',
      discussedWithHOD: '',
      dateOfDiscussion: null,
      responsiblePersonForClosure: '',
      status: 'Open',
      reasonForRejection: '',
      rejectedBy: '',
      eligibleForRecommendation: 'no',
      remarks: '',
      changeHistory: [],
    },
  ];

  for (const record of demoRecords) {
    await saveRecommendation(record);
  }
};