// utils/demoData.ts

// Helper function to convert date strings to Date objects
const toDateObject = (dateStr: string | null): Date | null => {
  if (!dateStr) return null;
  const date = new Date(dateStr);
  return isNaN(date.getTime()) ? null : date;
};

export const populateDemoData = async (saveRecommendation: Function) => {
  const demoRecords = [
    {
      // Row 1
      source: 'Apex',
      plantName: 'All',
      location: 'Angul',
      section: 'Operations',
      equipmentId: 'EQ-1001',
      equipmentType: 'Conveyor',
      equipmentDescription: 'Main Conveyor Belt System',
      recommendationDescription:
        'Centralized ARC to be done for structural integrity and all the requirements to be collated for the same and all technical requirements and documentation to be collated centrally for consistency and traceability.',
      recommendationType: 'safety_assurance',
      consequenceSelectionType: 'people',
      initialConsequence: '5',
      initialLikelihood: '4',
      initialRiskScore: '20',
      injuryPotential: 'multiplefatal',
      assetRepairCost: 500000,
      productionLossPerDay: 250000,
      potentialRiskImpactMin: 0.5,
      potentialRiskImpactMedium: 1.0,
      potentialRiskImpactMax: 2.5,
      finalConsequence: '2',
      finalLikelihood: '2',
      finalRiskScore: '4',
      benefitOfImplementation: 'Reduced risk of fatal accidents, improved safety compliance',
      estimatedCost: 1500000,
      shutdownRequirement: 'Yes',
      dateOfRecommendation: toDateObject('2026-04-08'),
      targetImplementationDate: toDateObject('2026-06-30'),
      actualImplementationDate: toDateObject('2026-07-15'),
      ageOfRecommendation: '83',
      benefitAnalysisTargetDate: toDateObject('2026-08-30'),
      numberOfOverdueDays: '15',
      recommendationInitiatedBy: 'ED Incharge',
      discussedWithHOD: 'Yes',
      dateOfDiscussion: toDateObject('2026-04-10'),
      responsiblePersonForClosure: 'Maintenance Manager',
      status: 'In-Progress',
      reasonForRejection: '',
      rejectedBy: '',
      eligibleForRecommendation: 'Yes',
      remarks: 'Requires coordination with multiple departments',
      changeHistory: [],
    },
    {
      // Row 2
      source: 'Apex',
      plantName: 'All',
      location: 'Angul',
      section: 'Maintenance',
      equipmentId: 'EQ-1002',
      equipmentType: 'Scaffolding',
      equipmentDescription: 'Steel Scaffolding System',
      recommendationDescription:
        'PM instructed to centrally collate plant-wide scaffolding data, including total tonnage requirements, total cubic meter area required so that this data will support planning, cost control, and for central ARC.',
      recommendationType: 'safety_assurance',
      consequenceSelectionType: 'people',
      initialConsequence: '5',
      initialLikelihood: '4',
      initialRiskScore: '20',
      injuryPotential: 'multiplefatal',
      assetRepairCost: 750000,
      productionLossPerDay: 300000,
      potentialRiskImpactMin: 0.8,
      potentialRiskImpactMedium: 1.5,
      potentialRiskImpactMax: 3.0,
      finalConsequence: '3',
      finalLikelihood: '2',
      finalRiskScore: '6',
      benefitOfImplementation: 'Improved safety standards, better resource planning, cost optimization',
      estimatedCost: 2000000,
      shutdownRequirement: 'No',
      dateOfRecommendation: toDateObject('2026-04-01'),
      targetImplementationDate: toDateObject('2026-06-15'),
      actualImplementationDate: toDateObject('2026-06-20'),
      ageOfRecommendation: '80',
      benefitAnalysisTargetDate: toDateObject('2026-07-20'),
      numberOfOverdueDays: '5',
      recommendationInitiatedBy: 'ED Incharge',
      discussedWithHOD: 'Yes',
      dateOfDiscussion: toDateObject('2026-04-05'),
      responsiblePersonForClosure: 'Operations Manager',
      status: 'Open',
      reasonForRejection: '',
      rejectedBy: '',
      eligibleForRecommendation: 'Yes',
      remarks: 'Data collection ongoing across all plants',
      changeHistory: [],
    },
    {
      // Row 3
      source: 'BHM',
      plantName: '1200 O2',
      location: 'Angul',
      section: 'Process Control',
      equipmentId: 'EQ-2001',
      equipmentType: 'Gas Detector',
      equipmentDescription: 'CO2 Analyzer System',
      recommendationDescription:
        'Additional CO2 detector to be installed in adsorber outlet to ensure accurate reading.',
      recommendationType: 'preventive',
      consequenceSelectionType: 'people',
      initialConsequence: '5',
      initialLikelihood: '4',
      initialRiskScore: '20',
      injuryPotential: 'fatal',
      assetRepairCost: 250000,
      productionLossPerDay: 100000,
      potentialRiskImpactMin: 0.3,
      potentialRiskImpactMedium: 0.8,
      potentialRiskImpactMax: 1.5,
      finalConsequence: '5',
      finalLikelihood: '2',
      finalRiskScore: '10',
      benefitOfImplementation: 'Early detection of CO2 leaks, improved worker safety',
      estimatedCost: 500000,
      shutdownRequirement: 'Yes',
      dateOfRecommendation: toDateObject('2025-08-08'),
      targetImplementationDate: toDateObject('2026-07-08'),
      actualImplementationDate: toDateObject('2026-07-25'),
      ageOfRecommendation: '236',
      benefitAnalysisTargetDate: toDateObject('2026-08-25'),
      numberOfOverdueDays: '17',
      recommendationInitiatedBy: 'ED Incharge',
      discussedWithHOD: 'Yes',
      dateOfDiscussion: toDateObject('2025-08-15'),
      responsiblePersonForClosure: 'Instrumentation Engineer',
      status: 'In-Progress',
      reasonForRejection: '',
      rejectedBy: '',
      eligibleForRecommendation: 'Yes',
      remarks: 'Installation in progress, awaiting calibration',
      changeHistory: [],
    },
    {
      // Row 4
      source: 'BHM',
      plantName: '1200 O2',
      location: 'Angul',
      section: 'Quality Control',
      equipmentId: 'EQ-2002',
      equipmentType: 'Analyzer',
      equipmentDescription: 'CO2 Quality Analyzer',
      recommendationDescription:
        'CO2 analyser calibration frequency to be increased from 4 months to shorter duration & CO2 analyser accuracy of reading should be periodically compared with quality control sampling.',
      recommendationType: 'preventive',
      consequenceSelectionType: 'quality',
      initialConsequence: '4',
      initialLikelihood: '3',
      initialRiskScore: '12',
      injuryPotential: 'none',
      assetRepairCost: 150000,
      productionLossPerDay: 50000,
      potentialRiskImpactMin: 0.2,
      potentialRiskImpactMedium: 0.5,
      potentialRiskImpactMax: 1.0,
      finalConsequence: '2',
      finalLikelihood: '1',
      finalRiskScore: '2',
      benefitOfImplementation: 'Improved accuracy, reduced quality incidents, better compliance',
      estimatedCost: 300000,
      shutdownRequirement: 'No',
      dateOfRecommendation: toDateObject('2026-02-15'),
      targetImplementationDate: toDateObject('2026-04-30'),
      actualImplementationDate: toDateObject('2026-05-15'),
      ageOfRecommendation: '75',
      benefitAnalysisTargetDate: toDateObject('2026-06-15'),
      numberOfOverdueDays: '15',
      recommendationInitiatedBy: 'Quality Manager',
      discussedWithHOD: 'Yes',
      dateOfDiscussion: toDateObject('2026-02-20'),
      responsiblePersonForClosure: 'Quality Control Head',
      status: 'Implemented',
      reasonForRejection: '',
      rejectedBy: '',
      eligibleForRecommendation: 'Yes',
      remarks: 'New calibration schedule implemented successfully',
      changeHistory: [],
    },
    {
      // Row 5
      source: 'BHM',
      plantName: '1200 O2',
      location: 'Angul',
      section: 'Safety',
      equipmentId: 'EQ-2003',
      equipmentType: 'Alarm System',
      equipmentDescription: 'Field Air Intake CO2 Alarm System',
      recommendationDescription:
        'Field air intake CO2 analyser to initiate an alarm for the operator to take action on high CO2 detection.',
      recommendationType: 'safety_assurance',
      consequenceSelectionType: 'people',
      initialConsequence: '5',
      initialLikelihood: '3',
      initialRiskScore: '15',
      injuryPotential: 'fatal',
      assetRepairCost: 180000,
      productionLossPerDay: 80000,
      potentialRiskImpactMin: 0.4,
      potentialRiskImpactMedium: 0.9,
      potentialRiskImpactMax: 1.8,
      finalConsequence: '3',
      finalLikelihood: '2',
      finalRiskScore: '6',
      benefitOfImplementation: 'Immediate alert on high CO2 levels, faster response time',
      estimatedCost: 450000,
      shutdownRequirement: 'No',
      dateOfRecommendation: toDateObject('2026-03-10'),
      targetImplementationDate: toDateObject('2026-05-10'),
      actualImplementationDate: toDateObject('2026-05-25'),
      ageOfRecommendation: '76',
      benefitAnalysisTargetDate: toDateObject('2026-06-25'),
      numberOfOverdueDays: '15',
      recommendationInitiatedBy: 'Safety Officer',
      discussedWithHOD: 'Yes',
      dateOfDiscussion: toDateObject('2026-03-15'),
      responsiblePersonForClosure: 'Safety Manager',
      status: 'Implemented',
      reasonForRejection: '',
      rejectedBy: '',
      eligibleForRecommendation: 'Yes',
      remarks: 'Alarm system tested and working properly',
      changeHistory: [],
    },
  ];

  for (const record of demoRecords) {
    await saveRecommendation(record);
  }
};