

export const APP_URL = {
  DEFAULT_APP_PATH: "/",
  DASHBOARD: "/dashboard",
  SAFETY_SI: "/si",
  SAFETY_SI_NEW: "/si/si-new",
  SAFETY_SI_SCHEDULE: "si/si-schedule",
  SAFETY_LW: "/lw",
  SAFETY_LW_NEW: "/lw/lw-new",
  SAFETY_LW_SCHEDULE: "lw/lw-schedule",
  SAFETY_SO: "/so",
  SAFETY_SO_NEW: "/so/so-new",
  INCIDENT_MANAGEMENT: "/incident-management",
  INCIDENT_DETAIL: "/incident-management/incident-details",
  SAFETY_ALERT: "/incident-management/safety-alert",
  PIR_EDIT: "/incident-management/pir-form-edit",
  LESSON_LEARNT: "/incident-management/lession-learnt",
  CONTRACTOR: "/contractor",
  CSM: "/csm",
  CSM_CFA_NEW: "csm/contractor-field-audit-new",
  BHM: "/bhm",
  // MY_PORTFOLIO: "/im/my-portfolio",
  MY_PORTFOLIO: "/my-draft",
  MY_DRAFT: "/im/my-draft",
  MY_ACTION: "/my-action",
  MY_SI: "/im/my-si",
  MY_SO: "/im/my-so",
  GLOBAL_ACTION: "/im/global-action",
  PIR: "/incident-management/pir-form",
  USER:"/si",
  CONTRACTOR_LOGIN: "/contractor-login",
  MOC_DASHBOARD: "/moc",
  CREATE_MOC: "/moc/create-moc",
  UPDATE_MOC: "/moc/update-moc",
  UPDATE_CHECKLIST_FORMS: "/moc/update-checklist-forms",
  CHECKLIST_FORMS : "/moc/checklist-forms",
  HOD_DETAIL_VIEW: "/moc/hoddetailview",
  HOD_PENDING: "/moc/hodpending",
  HOD_PENDING_EDIT: "/moc/hodpending-edit",
  HOD_CHECKLIST_VIEW: "/moc/hodomview",
  HOD_CHECKLIST_VIEW_EDIT: "/moc/hodomview-edit",
  ADMIN_DASHBOARD: "/admin",
  WORK_PLACE: "/admin/work-place",
  EMPLOYEE_MANAGE: "/admin/employee-manage",
  ROLE_MANAGE: "/admin/role-manage",
  REPORT_DASHBOARD: "/report-dashboard",
  REPORT_SI_SO_LW: "/report-si-so-lw",
  REPORT_IM: "/report-im",
  RECMD_TRACKER: "/recmd-tracker",
  CREATE_RECMD: "/recmd-tracker/create-recommendation",
  UPDATE_RECMD: "/recmd-tracker/update-recommendation"
  
  };
export const USER_ROLES = {
  ROLE_ADMIN: "Admin",
};
